### ISSUE TITLE
Fix permission issue w/ `superbuild-icubhead-withuser` docker image

### ISSUE THREAD

**Issue by MSECode** [icub-tech-iit/docker-deployment-images#11]
## Task description :memo:
Permission issue has been identified while using [superbuild-icubhead-withuser](https://github.com/icub-tech-iit/docker-deployment-images/tree/master/dockerfile_images/basic/superbuild-icubhead-withuser) docker image in `docker-compose` containers.
Specifically, the following error has been triggered when all the containers tried to start:
`Cannot start service ymotorgui: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/local/bin/entrypoint.sh": permission denied: unknown`
 An analysis of the files pushed with the image should be done, especially the entrypoint bash file: `/usr/local/bin/entrypoint.sh` and the steps used in the `Dockerfile` should be revised to check why image is not starting as expected.

## Definition of Done :white_check_mark:
Fix problem and be able to run containers with the default `icub` user without any permission error.

**Comment by valegagge** [comment]
this is the [PR](https://github.com/icub-tech-iit/docker-deployment-images/pull/12)
