### ISSUE TITLE
Analyze error regarding deployment failure when a job is triggered

### ISSUE THREAD

**Issue by MSECode** [icub-tech-iit/docker-deployment-images#15]
Since around 3 month ago, it seems to be a problem in the starting phase when a job using github event REST API are used.
Here a screen of the type of failure is reported. 

![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/dd7f179e-8b65-4e53-9753-ecdeef3b8fb5)

It seems that the problem is related, not to the use of the env variables but more to the use of the event REST API, which should not be deprecated  as documented here: 
https://docs.github.com/en/rest/overview/github-event-types?apiVersion=2022-11-28

The job previously were executing fine, as shown by the previous job. Since a couple of months ago, they are starting to fail.

cc: @valegagge @pattacini

**Comment by pattacini** [comment]
https://github.com/icub-tech-iit/docker-deployment-images/blob/2961c08bc4fc39c75e03adbf2d5371fddcb2723b/.github/workflows/release.yml#L62

Isn't there a typo?

I guess it should `${{ env.REPOSITORY_NAME_ONLY }}`

**Comment by MSECode** [comment]
> https://github.com/icub-tech-iit/docker-deployment-images/blob/2961c08bc4fc39c75e03adbf2d5371fddcb2723b/.github/workflows/release.yml#L62
> 
> Isn't there a typo?
> 
> I guess it should `${{ env.REPOSITORY_NAME_ONLY }}`

Yep, I double checked now. I didn't catch it at a first look.
Sorry for that. I'll do a commit on the test project to check if it's that and then I'll commit the fix here.
