### ISSUE TITLE
Check the automatic compilation on Superbuild release event

### ISSUE THREAD

**Issue by valegagge** [icub-tech-iit/docker-deployment-images#2]
We want to verify that the automatic compilation works correctly on `Superbuild` release event.

**DoD**
The automatic compilation works correctly on `Superbuild` release event.

**Comment by valegagge** [comment]
@valegagge /remind  20 January 2023

**Comment by valegagge** [comment]
The last release v2023.02.3 triggered the action and the entire pipeline works fine. 

I add just a reminder for the next release because there were a lot of changes: the major one is the publication on the git hub registry.

@valegagge @MSECode  /remind 30 May 2023

**Comment by MSECode** [comment]
Compilation triggered by superbuild works fine. However for the latest release the image compilation failed due to a typo in the workflow file.
Do we, then, need to trigger the release job manually?

@valegagge

**Comment by valegagge** [comment]
> Compilation triggered by superbuild works fine. However for the latest release the image compilation failed due to a typo in the workflow file. Do we, then, need to trigger the release job manually?
> 
> @valegagge

Yes, I just triggered it by hand. 

cc @MSECode 

We need to check if it works properly

**Comment by valegagge** [comment]
The automatic compilation has been triggered correctly, therefore I'm closing this issue.

Related to the compilation errors, please check this issue #14
