### ISSUE TITLE
Docker run fail

### ISSUE THREAD

**Issue by TheArmega** [icub-tech-iit/docker-deployment-images#21]
Im trying to run the master-stable_binaries docker but when runnig the command: 
docker run -it --rm ghcr.io/icub-tech-iit/docker-deployment-images/cd_superbuild-ros2:master-stable_binaries /bin/bash

I get the following message error:
usr/local/bin/setup_robotology_tdd.sh: line 3: /opt/ros//setup.bash: No such file or directory

I have tried to setup an  environment variable as: ROS_DISTRO=humble
But still having the same error msg

**Comment by pattacini** [comment]
cc @valegagge @MSECode

**Comment by MSECode** [comment]
I'm gonna look into that.

Thanks for the feedback.
In the meanwhile you can try using the `sources` image instead of binaries even if it will take linger to download and build.

**Comment by MSECode** [comment]
Opened the PR with the fix here: https://github.com/icub-tech-iit/docker-deployment-images/pull/22

cc: @valegagge @pattacini @martinaxgloria @TheArmega

**Comment by valegagge** [comment]
Hi @TheArmega ,
we still have a problem with the binary image, but the source image should work fine.

The [`master-stable-source`](https://github.com/icub-tech-iit/docker-deployment-images/pkgs/container/docker-deployment-images%2Fcd_superbuild-ros2/149159320?tag=master-stable_sources) now works as expected. 
Could the source image work for you? 

Cheers 
Valentina

**Comment by valegagge** [comment]
Hi @TheArmega,
now also the [master-stable_binaries](https://github.com/icub-tech-iit/docker-deployment-images/pkgs/container/docker-deployment-images%2Fcd_superbuild-ros2/151404448?tag=master-stable_binaries) image is available.

Cheers 
Valentina

**Comment by MSECode** [comment]
I checked the built binaries image too.
Here's the results that show that the images have been built as expected:

![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/905de796-deb2-4cff-98c0-980609f6170f)

![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/980170b7-f54d-48b0-9263-ffc32ec67338)
