### ISSUE TITLE
Reorganize the available docker images

### ISSUE THREAD

**Issue by valegagge** [icub-tech-iit/docker-deployment-images#25]
After this pull https://github.com/orgs/robotology/discussions/660,
 we decided to maintain only the following images:

- ` superbuild-icubhead`
- `superbuild-icubhead-withuser`
- `superbuild-icubtest`
- `superbuild`

We still have to decide how to build images with gazebo, ros2, and superbuild.

**Dod**
 - have a clear idea of which docker images we keep, especially referring to gazebo, ros2, etc
 - purge the images from unuseful stuff
 - test the images

**Comment by valegagge** [comment]
After a discussion inside silo-sw, we decide to keep an image `superbuild+gazebo ` and another `superbuild + ros2 + gazebo`.

**Comment by MSECode** [comment]
I'll post here some ideas about updates that can be imported in the images to clean them up and to have a clear idea of what all the steps in the Dockerfile are doing:
- superbuild:
    - is it a good idea to remove the folder superbuild/build/src/** after compilation and installation to make the final image smaller
    - how to deal with multistage docker build, this may be helpful https://medium.com/@lexitrainerph/multistage-image-builds-in-docker-a-comprehensive-guide-from-basics-to-mastery-5884b547950
    - check is specific repos from appsAway are still needed or checks and dependencies are now integrated in superbuild
-

**Comment by MSECode** [comment]
We can close this issue and then open a new one in which we keep the upcoming updates that should be discussed.
