### ISSUE TITLE
Create a new docker image and update the automatic compilation actions

### ISSUE THREAD

**Issue by valegagge** [icub-tech-iit/docker-deployment-images#31]
## Task description :memo:
- Create a new docker image with [robometry](https://github.com/robotology/robometry)
- update the automatic compilation of this new image

## Definition of Done :white_check_mark:
- [x] The image has been tested. (YRI runs with the device [TelemetryDeviceDumper](https://github.com/robotology/robometry?tab=readme-ov-file#telemetrydevicedumper) es expected)
- [x] The image is available in github registry.
- [x] Actions updated

**Comment by MSECode** [comment]
I've created the image based on `ghcr.io/icub-tech-iit/docker-deployment-images/cd_superbuild-icubhead` with all the corresponding tags:
- stable, unstable
- sources, binaries

that uses the option `DROBOTOLOGY_ENABLE_DYNAMICS:BOOL=ON ` for compiling superbuild with robometry.

I've tested that the compilation worked fine for both sources and binaries images and running the corresponding containers I've checked that the plugin telemetryDeviceDumper was correctly installed.
Here the outputs of the building of the images locally and the checks

![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/54813f6f-fe20-463d-947d-8251279962da)

![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/96be9568-d526-457a-91b7-7a9b9975eda2)


![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/aadc3742-cefc-4449-a991-f0b5b86527fe)

![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/51ca7d3a-1eb2-4e49-9d53-01cc8826beed)

**Comment by valegagge** [comment]
@MSECode PR merged. tomorrw we can check if the new image is available on github registry and use it! 💪

**Comment by MSECode** [comment]
Here the output of the tests:

![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/9dd8d9e4-0ae7-446d-b5ee-3480871e0675)

![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/7eadfe8a-a8c3-4ec3-ae50-27fc63ad5000)

**Comment by valegagge** [comment]
Dod satisfied. 
Closing.
